name: mikrotik_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  router_os_client: ^2.0.0
  dio: ^5.5.0+1
  mqtt_client: ^10.2.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5
  csv: ^6.0.0
  pdf: ^3.10.8
  printing: ^5.14.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.11.0
  camera: ^0.10.6
  path: ^1.9.0
  share_plus: ^11.1.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  marquee_widget: ^1.2.0
  provider: ^6.1.2
  device_info_plus: ^10.1.0
  uuid: ^4.4.0
  graphview: ^1.2.0
  dart_ping: ^8.0.1
  file_picker: ^8.0.0+1   # <-- ✨ الحزمة الجديدة التي تمت إضافتها
  syncfusion_flutter_pdf: ^26.1.39
  image: ^4.5.4
  google_mlkit_document_scanner: ^0.4.0
  network_info_plus: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_app_name: ^0.1.1

flutter:
  uses-material-design: true

flutter_app_name:
  name: "اداره الكروت"

# --- ✨ تم إضافة هذا القسم لحل مشكلة التعارض ---
dependency_overrides:
  xml: ^6.3.0